name: CI

on:
  # build on PR creation/updates, also when pushing to master/develop, or create a release
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master, develop]
    tags: [v*]


env:
  REPO_NAME_SLUG: dw3b
  PR_NUMBER: ${{ github.event.number }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Set output of cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache generated files
        id: cache-generated-files
        uses: actions/cache@v2
        with:
          path: |
            src/abis/types
            src/locales
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Load dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Load generated files
        id: cache-generated-files
        uses: actions/cache@v2
        with:
          path: |
            src/abis/types
            src/locales
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

      - name: Unit Test
        run: yarn test

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Load dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Load generated files
        id: cache-generated-files
        uses: actions/cache@v2
        with:
          path: |
            src/abis/types
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
          github_token: ${{ secrets.github_token }}
          auto_fix: ${{ github.event_name == 'pull_request' }}

  deploy:
    name: Deploy to GH Pages
    needs: build
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Load dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Load generated files
        id: cache-generated-files
        uses: actions/cache@v2
        with:
          path: |
            src/abis/types
            src/locales
          key: ${{ runner.os }}-generatedFiles-${{ hashFiles('**/yarn.lock') }}

      - name: Build Web Apps
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build